config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('drive.urls')),
]

drive/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('students/', views.students_view, name='students'),
    path('students/add/', views.user_add, name='user_add'),

    path('profile/<int:pk>', views.student_detail, name='student_detail'),
    path('profile/edit/<int:pk>', views.user_edit, name='user_edit'),
    path('user/delete/<int:pk>', views.user_delete, name='user_delete'),

    path('permits/', views.permits_view, name='permits'),
    path('permits/add/', views.permit_add, name='permit_add'),
    path('permits/edit/<int:pk>', views.permit_edit, name='permit_edit'),
    path('permits/delete/<int:pk>', views.permit_delete, name='permit_delete'),
    path('permits/<int:pk>/course/add/', views.course_add, name='course_add'),
    path('permits/<int:p_pk>/course/delete/<int:pk>', views.course_delete, name='course_delete'),
    path('permits/course/<int:pk>/edit/', views.course_edit, name='course_edit'),
    path('permits/course/<int:pk>', views.course_detail, name='course_detail'),
    path('permit/<int:pk>', views.permit_detail, name='permit_single'),

    path('course/<int:course_id>/instructor/edit/', views.select_instructor, name='add_instructor'),
    path('course/<int:course_id>/instructor/confirm/<int:student_id>', views.confirm_select_instructor, name='confirm_instructor'),
    path('course/<int:course_id>/instructor/delete/<int:student_id>', views.confirm_delete_instructor, name='delete_instructor'),

    path('ajax/filter_course/', views.filter_courses_view, name='filter_views'),

    re_path(r'^$', views.home_view, name='home'),

    path('payment/all/', views.payment_deadlines, name='payment'),
    path('payment/current/', views.done_payments, name='current_payments'),
    path('administrator/<int:extra_time>', views.admin_view, name='administrator'),
    path('deadline/delete/<int:pk>', views.delete_payment, name='delete_payment'),

]

drivy/drivy/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

drive/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Student, Grade, Course, Permit, payment_deadlines


# Add/Edit User profile
class UpdateProfile(forms.ModelForm):
    is_super = forms.BooleanField(required=False)

    class Meta:
        model = Student
        fields = ('first_name', 'last_name', 'email', 'course', 'permit', 'country', 'city', 'user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].widget.attrs.update({'hidden': True})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Last Name'})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Email'})
        self.fields['permit'].widget.attrs.update({'class': 'form-control'})
        self.fields['country'].widget.attrs.update({'class': 'form-control'})
        self.fields['city'].widget.attrs.update({'class': 'form-control', 'placeholder': 'City'})
        self.fields['course'].widget.attrs.update({'class': 'full-width', 'hidden': True, 'required': False})


# Sign up form
class SignUpForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        try:
            User.objects.get(username__iexact=self.username)
            raise forms.ValidationError('User already exists')
        except User.DoesNotExist:
            return self.username

    def clean_password(self):
        pw1 = self.cleaned_data.get('password1')
        pw2 = self.cleaned_data.get('password2')

        if pw1 and pw2 and pw1 == pw2:
            return pw1
        raise forms.ValidationError("Password doesn't match")


# Select teachers for a specific course
class SelectInstructorsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('first_name', 'last_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'] = forms.ModelMultipleChoiceField(queryset=Student.objects.all())
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})


class GradeStudentsForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = ('student', 'grade',)

    def __init__(self, *args, **kwargs):
        super(GradeStudentsForm, self).__init__(*args, **kwargs)
        self.fields['student'].widget.attrs.update({'class': 'form-control'})
        self.fields['grade'].widget.attrs.update({'class': 'form-control'})


class DateInput(forms.DateInput):
    input_type = 'date'


class CourseAddForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        widgets = {
            'start_date': DateInput(),
            'end_date': DateInput()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['summary'].widget.attrs.update({'class': 'form-control'})
        self.fields['permit'].widget.attrs.update({'class': 'form-control'})
        self.fields['start_date'].widget.attrs.update({'class': 'form-control'})
        self.fields['end_date'].widget.attrs.update({'class': 'form-control'})
        self.fields['cost'].widget.attrs.update({'class': 'form-control'})


class PermitForm(forms.ModelForm):
    class Meta:
        model = Permit
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['summary'].widget.attrs.update({'class': 'form-control'})


class DeadlinesForm(forms.ModelForm):
    class Meta:
        model = payment_deadlines
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})

#

drive/views.py
from datetime import datetime
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import redirect
from .models import Course, Permit, Student, Grade, payment_deadlines, Payment
from django.contrib.auth.models import User
from django.db.models import Avg, Max, Min, Count
from .forms import UpdateProfile, CourseAddForm, PermitForm, DeadlinesForm
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from django import forms
from django.template.defaulttags import register

max_counter = 3


@register.filter
def toInt(value):
    return int(value)


@register.filter
def toStr(value):
    return str(value)


@register.filter
def addOne(value):
    value = value + 1
    return value


@register.filter
def get_grade(course, user):
    grade = list(Grade.objects.values_list('grade', flat=True).filter(course__pk=course, student__pk=user))
    if not grade:
        return 0
    return grade[0]


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


@register.filter
def sub(value, arg):
    return value - arg


def permits_view(request):
    permits = Permit.objects.all()

    if request.user.is_authenticated:
        return render(
            request,
            'permits_list.html',
            {'permits': permits},
        )
    else:
        return redirect('login')


def permit_add(request):
    if request.method == 'POST':
        form = PermitForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('permits')
    else:
        form = PermitForm()

    return render(
        request, 'permit_add.html', {'form': form},
    )


def permit_delete(request, pk):
    permit = Permit.objects.get(pk=pk)
    permit.delete()

    return redirect('permits')


def permit_edit(request, pk):
    permit = Permit.objects.get(pk=pk)

    if request.method == 'POST':
        form = PermitForm(request.POST, instance=permit)
        if form.is_valid():
            form.save()
            return redirect('permits')
    else:
        form = PermitForm(instance=permit)

    return render(
        request, 'program_add.html', {'form': form},
    )


def permit_detail(request, pk):
    permit = Permit.objects.get(pk=pk)
    courses = Course.objects.filter(permit_id=pk)

    paginator = Paginator(courses, 10)
    page = request.GET.get('page')

    courses = paginator.get_page(page)

    if request.user.is_authenticated:
        return render(
            request,
            'permit_single.html',
            {'permit': permit, 'courses': courses, 'credits': credits},
        )
    else:
        return redirect('login')


def students_view(request):
    students = Student.objects.all()
    permits = Permit.objects.all()

    if request.method == 'GET':
        p = request.GET.get('permit', '')
        name = request.GET.get('name', '')
        email = request.GET.get('email', '')

        if p != '':
            students = Student.objects.filter(permit=p, first_name__contains=name, email__contains=email)
        else:
            students = Student.objects.filter(first_name__contains=name, email__contains=email)

    if request.user.is_authenticated:
        return render(
            request,
            'students_list.html',
            {'students': students, 'permits': permits},
        )
    else:
        return redirect('login')


def student_detail(request, pk):
    student = Student.objects.get(pk=pk)
    success = Grade.objects.filter(student=student.user).order_by('-grade')
    details = Grade.objects.filter(student=student.user, grade__gt=4).aggregate(Avg('grade'), Max('grade'),
                                                                                Min('grade'))

    if request.user.is_authenticated:
        return render(
            request, 'student_profile.html', {'student': student, 'success': success, 'details': details},
        )
    else:
        return redirect('login')


def course_detail(request, pk):
    course = Course.objects.get(pk=pk)
    users = User.objects.filter(student__course_instructor__in=[course])
    grades = Grade.objects.filter(student_id=request.user.id, course_id=pk)
    instructors = Student.objects.filter(course_instructor__in=[course])

    if request.user.is_authenticated:
        return render(
            request, 'course_single.html',
            {'usrs': users, 'course': course, 'grades': grades, 'instructors': instructors},
        )
    else:
        return redirect('login')


def update_instructor(pk_t1):
    pk_t1 = int(pk_t1)
    if pk_t1 > 0:
        course = Course.objects.latest('pk')
        t1 = User.objects.get(pk=pk_t1)

        if not User.objects.filter(student__course_instructor__in=[course], pk=pk_t1).exists():
            t1.student.course_instructor.add(course)


def course_add(request, pk):
    users = User.objects.all()
    if request.method == 'POST':
        form = CourseAddForm(request.POST)
        if form.is_valid():
            form.save()
            update_instructor(request.POST.get('user_1'))
            if request.POST.get('submit') != 'Save':
                return redirect('course_add', pk=pk)
            return redirect('permit_single', pk=request.POST.get('permit'))
    else:
        form = CourseAddForm(initial={'permit': Permit.objects.get(pk=pk)})

    if request.user.is_authenticated and request.user.is_superuser:
        return render(
            request, 'course_add.html', {'form': form, 'permit': pk, 'users': users},
        )
    else:
        return redirect('login')


def course_edit(request, pk):
    users = User.objects.all()
    course = get_object_or_404(Course, pk=pk)
    if request.method == 'POST':
        form = CourseAddForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('permit_single', pk=request.POST.get('permit'))
    else:
        form = CourseAddForm(instance=course)

    # print(form.errors)

    if request.user.is_authenticated and request.user.is_superuser:
        return render(
            request, 'course_add.html', {'form': form, 'permit': pk, 'users': users, 'course': pk},
        )
    else:
        return redirect('login')


def course_delete(request, pk, p_pk):
    course = Course.objects.get(pk=pk)
    course.delete()

    return redirect('permit_single', pk=p_pk)


def user_add(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            uid = Student.objects.latest('pk').pk
            return redirect('user_edit', pk=uid)
    else:
        form = UserCreationForm()

    print(form.errors)

    if request.user.is_authenticated and request.user.is_superuser:
        return render(
            request, 'user_add.html', {'form': form},
        )
    else:
        return redirect('login')


def user_delete(request, pk):
    usr = get_object_or_404(User, pk=pk)
    usr.delete()

    return redirect('students')


def user_edit(request, pk):
    student = Student.objects.get(pk=pk)

    instance = get_object_or_404(Student, pk=pk)
    if request.method == 'POST':
        form = UpdateProfile(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save(commit=False)

            courses = request.POST.getlist('course')

            is_super = request.POST.get('is_super')

            if is_super:
                usr = User.objects.get(pk=student.user.pk)
                usr.is_admin = True
                usr.is_staff = True
                usr.is_superuser = True
                usr.save()

            for c in courses:
                grade = Grade()
                usr = User.objects.get(pk=request.POST.get('user'))
                crs = Course.objects.get(pk=c)
                if not Grade.objects.filter(course=crs, student=usr).exists():
                    grade.student = usr
                    grade.grade = 0
                    grade.course = crs
                    grade.save()

            existing_courses = list(Student.objects.values_list('course', flat=True).filter(pk=pk))

            for c in existing_courses:
                if str(c) not in courses:
                    Grade.objects.filter(student=User.objects.get(pk=request.POST.get('user')), course=c).delete()

            form.save()
            return redirect('students')
    else:
        form = UpdateProfile(instance=instance,
                             initial=({'is_super': User.objects.get(pk=student.user.pk).is_superuser}))

    return render(
        request, 'user_profile_edit.html', {'form': form, 'student': student},
    )


def select_instructor(request, course_id):
    students = Student.objects.all()
    curr_instructor = Student.objects.filter(course_instructor__in=[Course.objects.get(pk=course_id)])

    if request.method == 'GET':
        first_name = request.GET.get('first_name', '')
        last_name = request.GET.get('last_name', '')
        students = Student.objects.filter(first_name__contains=first_name, last_name__contains=last_name).exclude(
            course_instructor__in=[Course.objects.get(pk=course_id)])

    paginator = Paginator(students, 15)

    page = request.GET.get('page')
    students = paginator.get_page(page)

    return render(
        request, 'select_instructor.html',
        {'students': students, 'course_id': course_id, 'instructors': curr_instructor},
    )


def confirm_select_instructor(request, course_id, student_id):
    student = Student.objects.get(pk=student_id)
    course = Course.objects.get(pk=course_id)

    student.course_instructor.add(course)
    student.save()

    return redirect('add_instructor', course_id=course_id)


def confirm_delete_instructor(request, course_id, student_id):
    student = Student.objects.get(pk=student_id)
    course = Course.objects.get(pk=course_id)

drive/templates/admin_panel.html
{% extends 'base_generic.html' %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="card-box">
                <h6>Manage Payments</h6>
                <small class="faded">Create new / delete / modify payments</small>
                <hr>
                <!-- <br> -->
                <form method="post">
                    {% csrf_token %}
                    <table>
                        <thead>
                        <tr>
                            <th style="max-width: 40px">Active</th>
                            <th>Payment</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {{ formset.management_form }} {% for form in formset %}
                        {{ form.id }}
                        <tr>
                            <td class="text-center" style="max-width: 40px">{{ form.active }}</td>
                            <td>{{ form.name }}</td>
                            <td class="text-center">{% if form.id.value %}<small><a class="text-danger"
                                                                                    href="{% url 'delete_payment' pk=form.id.value %}">Delete</a></small>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if formset|length == 0 %}
                    <p class="lead">No payments</p>
                    {% endif %}
                    <br>
                    <a class="float-right btn btn-primary" href="{% url 'administrator' extra_time=extra|add:1 %}">+</a>
                    <input class="float-left btn btn-primary" type="submit" value="Save Changes">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

drive/templates/base_generic.html
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- <script src="https://cdn.ckeditor.com/ckeditor5/10.0.1/classic/ckeditor.js"></script> -->
    <title>Document</title>
</head>

<body>
    <div class="wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="no-padding col-md-1 col-sm-4">
                    <header>
                        <nav>
                            {% url 'home' as hom %} {% url 'students' as acc %} {% url 'permits' as prog %} {% url 'login' as log %} {% url 'student_detail' pk=user.student.pk as sd %}
                            <a href="{% url 'home' %}" {% if request.path == hom %} class="active" {% endif %}>Home</a>
                            <a href="{% url 'students' %}" {% if request.path == acc %} class="active" {% endif %}>Accounts</a>
                            <a href="{% url 'permits' %}" {% if request.path == prog %} class="active" {% endif %}>Courses</a>
                            <div>
                                {% if not user.is_authenticated %}
                                <a href="{% url 'login' %}" {% if request.path == log %} class="active" {% endif %}>Login</a> {% else %}
                                <div class="dd">
                                    <a {% if request.path == sd %} class="active" {% endif %}>{{ user.student.first_name }}</a>
                                    <div class="dd-menu">
                                        <ul>
                                            <a href="{% url 'student_detail' pk=user.student.pk %}">
                                                <li>Profile</li>
                                            </a>
                                            <a href="{% url 'administrator' extra_time=0 %}">
                                                <li>Admin panel</li>
                                            </a>
                                            <a class="text-danger" href="{% url 'logout' %}">
                                                <li>Logout</li>
                                            </a>
                                        </ul>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                        </nav>
                    </header>
                </div>
                <div class="col-md-11 col-sm-8">
                    <br>
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% block javascript %} {% endblock %}
    <script>
    var btn = $('.with-popup');
    var ddBtn = $('.dd');

    var expanded = false;

    ddBtn.click(function() {
        if (!expanded) {
            $(this).addClass('minus');
        } else {
            $(this).removeClass('minus');
        }

        expanded = !expanded;

        $('.dd-menu', this).slideToggle();
    });

    if (btn.length > 0) {
        function close_popups() {
            $('.popup').css('display', 'none');
        }

        $(document).keyup(function(e) {
            if (e.keyCode == 27)
                close_popups();
        });

        $(document).click(function(e) {
            if ($(e.target).closest(btn).length === 0) {
                close_popups();
            }
        })

        btn.click(function() {
            close_popups();
            $('.popup', this).css('display', 'block');
        });
    }
    </script>
</body>

</html>

drive/templates/course_add.html
{% extends 'base_generic.html' %} {% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-8 col-xs-12">
                <div class="card-box">
                    <h6>Add Course</h6>
                    <div class="form-group">
                        <span class="faded">Course name</span> {{ form.name }}
                    </div>
                    <div class="form-group">
                        <span class="faded">Summary</span> {{ form.summary }}
                    </div>
                    <div class="form-group">
                        <span class="faded">Cost $</span> {{ form.credits }}
                    </div>
                </div>
                <div class="card-box">
                    <h6>Date</h6>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <span class="faded">Start</span> {{ form.start_date }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <span class="faded">End</span> {{ form.end_date }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="empty-box">
                    <input class="btn btn-primary" name="submit" type="submit" value="Save"/>
                    <input class="btn btn-primary" name="submit" type="submit" value="Save & add new course"/>
                    <a class="no-float btn btn-danger" href="#">Return</a>
                </div>
            </div>
            {% url 'course_add' pk=permit as add_course %}
            <div class="col-md-4 col-xs-12">
                {% if request.path == add_course %}
                <div class="card-box">
                    <h6>Instructor</h6>
                    <div id="msg" role="alert">
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <select class="form-control" id="user_1" name="user_1">
                                <option value="0">None</option>
                                {% for u in users %}
                                <option value="{{ u.pk }}">{{ u }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <small class="faded">You can add more instructors later</small>
                    </form>
                </div>
                {% endif %}
                <div class="card-box">
                    <h6>Licence</h6>
                    <div class="form-group">
                        {{ form.permit }}
                    </div>
                </div>
                <div class="card-box">
                    <h6>State</h6>
                    <label>
                        {{ form.obligative }} Mandatory
                    </label>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %} {% block javascript %} {% load static %}
<script src="{% static 'js/ajax.js' %}"></script>
{% endblock %}

drive/templates/course_single.html
{% extends 'base_generic.html' %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-xs-12">
            <div class="no-shade card-box">
                <h4>{{ course }}</h4> {% if course.summary %}
                <p>{{ course.summary }}</p>
                {% endif %} {% if instructors %}
                <h6>Instructor(s)</h6> {% for instructor in instructors %}
                <a href="{% url 'student_detail' pk=instructor.pk%}">{{ instructor.first_name }} {{ instructor.last_name }}</a>
                <br/> {% endfor %} {% endif %}
            </div>
            {% load static %}
        </div>
    </div>
</div>
{% endblock %}

drive/templates/home.html
{% extends 'base_generic.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="card-box">
                <h6>Programs</h6>
                <ul class="list-unstyled">
                    {% for permit in permits %}
                    <a href="{% url 'permit_single' pk=permit.pk %}"><li>{{ permit.name }}</li></a>
                    {% endfor %}
                </ul>
            </div>
        </div>
        </div>
        <div class="col-md-12 col-xs-12">
            <div class="empty-box">
                <a href="{% url 'current_payments' %}" class="btn btn-primary">Payments</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

drive/templates/permit_add.html
{% extends 'base_generic.html' %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-xs-12">
            <form method="post">
                <div class="card-box">
                    {% csrf_token %}
                    <h6>Add Program</h6>
                    <div class="form-group">
                        Permit name<br>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        Summary<br>
                        {{ form.summary }}
                    </div>
                </div>
                <div class="empty-box">
                    <button class="btn btn-primary" type="submit">Save Permit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

drive/templates/user_profile_edit.html
{% extends 'base_generic.html' %}


{% block javascript %}
{% load static %}
<script src="{% static 'js/ajax.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
    <form enctype="multipart/form-data" method="post">
        <div class="row">
            <div class="col-md-6">
                <div class="card-box">
                    <h6>Personal info</h6><br/>
                    {% csrf_token %}
                    {{ form.user }}
                    <div class="form-group">
                        {{ form.first_name }}
                    </div>
                    <div class="form-group">
                        {{ form.last_name }}
                    </div>
                    <div class="form-group">
                        {{ form.email }}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card-box">
                    <h6>Location</h6><br/>
                    <div class="form-group">
                        {{ form.country }}
                    </div>
                    <div class="form-group">
                        {{ form.city }}
                    </div>
                </div>
                <div class="card-box">
                    <h6>Driving Licence</h6><br/>
                    <div class="form-group">
                        {{ form.permit }}
                    </div>
                    <div class="form-group position-relative">
                    </div>
                </div>
                {% if user.is_superuser %}
                <div class="no-shade card-box">
                    <div class="form-check">
                        {{ form.is_super }}
                        <label class="form-check-label" for="id_is_super">
                            Superuser
                        </label>
                    </div>
                </div>
                {% endif %}
                <div class="empty-box">
                    <button class="btn btn-primary" type="submit">Save</button>
                    <a class="btn btn-danger" href="{% url 'student_detail' pk=student.pk%}">Back</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}